### registro de cuentas de aspirantes
POST http://localhost:9870/hw/core/v1/auth/register/applicant HTTP/1.1
Content-Type: application/json

{
    "personalEmail": "keyla.martinez@test.com",
    "firstname": "Keyla Alexandra",
    "lastname": "Martinez",
    "address": "CostaRica San Jose 78362",
    "dni": "918-00433-3367",
    "phoneNumber": "+5120548954",
    "birthdate": "2001-04-22",
    "nationality": "Colombiana",
    "initAccu": 22.0
}


#### registro de cuentas de profesor
POST http://localhost:9870/hw/core/v1/auth/register/professor HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMwZWQ1ODliLWYxOTMtNDk2OC05MGI0LThhNWM0MTY1NjY1ZiIsInJvbCI6Imludml0YWRvIiwiaWF0IjoxNzA3OTU1NjEzLCJleHAiOjE3MDc5NTYyMTN9.NwpVl0R7u1vWTVXKxVf4AdZ92MTXUygLU8nJF3ztCTI

{
    "personalEmail": "lkmarsell@test.com",
    "firstname": "Lukas",
    "lastname": "Marsell",
    "password": "Lamisma123*"
}


### RESET USER ACCOUNT PASSWORD
PATCH  http://localhost:9870/hw/core/v1/auth/password/applicant HTTP/1.1
Content-Type: application/json

{
    "username": "lmarsell-3r5",
    "newPassword": "Lamisma123*",
    "prevPassword": "9jNDdd4YYV@"
}


### user login
POST  http://localhost:9870/hw/core/v1/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "lmarsell-3r5",
    "password": "Lamisma123*"
}


### realizar upgrade de cuenta de usaurio invitado a estudiante
PATCH  http://localhost:9870/hw/core/v1/auth/guest/4ff2c28f-9e4f-4155-9167-19564c187b0b/upgrade-to-student HTTP/1.1
Content-Type: application/json


### realizar refresco de token
PUT  http://localhost:9870/hw/core/v1/auth/refresh-token/30ed589b-f193-4968-90b4-8a5c4165665f HTTP/1.1
Content-Type: application/json