### registro de cuentas de aplicantes
POST http://localhost:9870/hw/core/v1/auth/register/applicant HTTP/1.1
Content-Type: application/json

{
    "personalEmail": "lucas.marsell@test.com",
    "firstname": "Lucas Andres",
    "lastname": "Marsell",
    "address": "Managua Distrito I B. Rev",
    "dni": "908-6767EW-89EW",
    "phoneNumber": "+5053728323",
    "birthdate": "2005-09-16",
    "nationality": "Nicaraguense"
}
